Re-add required jobs for sanity with condition and pick up newest workflow changes
Signed-off-by: Johann Hoffmann <johann.hoffmann@mailbox.org>

diff --git a/.github/workflows/ow_sdk_docker-compose.yml b/.github/workflows/ow_sdk_docker-compose.yml
--- a/.github/workflows/ow_sdk_docker-compose.yml
+++ b/.github/workflows/ow_sdk_docker-compose.yml
@@ -1,4 +1,4 @@
-name: 2.x SDK testing with Docker Compose deployment
+name: 2.x testing with Docker Compose deployment
 env:
   # thirdparties
   DOCKER_SERVER: tip-tip-wlan-cloud-docker-repo.jfrog.io
@@ -17,11 +17,11 @@ on:
   workflow_dispatch:
     inputs:
       testbeds:
-        default: 'basic-05'
+        default: 'basic-01,basic-02,basic-03,basic-04,basic-05,basic-06,basic-07,basic-08'
         description: 'Testbed(s) to test'
-        required: true
+        required: false
       marker_expression:
-        default: 'sdk_restapi'
+        default: 'uc_sanity'
         description: 'Markers expression that will be passed to the pytest command.'
         required: true
       owgw_version:
@@ -214,6 +214,8 @@ jobs:
         kind: Pod
         metadata:
           name: openwifi-docker-compose-${{ github.run_id }}
+          annotations:
+            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
           labels:
             app: openwifi-docker-compose-${{ github.run_id }}
         spec:
@@ -344,11 +346,92 @@ jobs:
       run: |
         docker run --rm -e OWSEC="$OWSEC" -e OWSEC_USERNAME="$OWSEC_USERNAME" -e OWSEC_PASSWORD="$OWSEC_PASSWORD" tip-tip-wlan-cloud-ucentral.jfrog.io/clustersysteminfo:main
 
-  test:
+  generate-matrix:
+    name: generate testbed matrix
     runs-on: ubuntu-latest
-    needs: [ build, deploy-controller ]
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+    - name: generate-matrix
+      id: set-matrix
+      run: |
+        TESTBEDS="${{ github.event.inputs.testbeds || 'basic-01,basic-02,basic-03,basic-04,basic-05,basic-06,basic-07,basic-08' }}"
+        TESTBEDS=$(echo $TESTBEDS | sed "s/,/\",\"/g" | sed 's/^/[\"/g' | sed 's/$/\"]/g')
+        TESTBEDS=$(echo "$TESTBEDS" | jq -c 'map({"testbed":.})')
+        echo "::set-output name=matrix::{\"include\":${TESTBEDS}}"
+
+  set-redirector-url:
+    needs: [ deploy-controller, generate-matrix ]
+    if: ${{ github.event.inputs.marker_expression }} == 'uc_sanity'
     strategy:
       fail-fast: false
+      matrix: ${{ fromJson( needs.generate-matrix.outputs.matrix ) }}
+    runs-on: self-hosted
+    steps:
+    - name: checkout testing repo
+      uses: actions/checkout@v2
+      with:
+        repository: Telecominfraproject/wlan-testing
+        path: wlan-testing
+        ref: WIFI-3620
+
+    - name: checkout pki cert scripts repo
+      uses: actions/checkout@v2
+      with:
+        repository: Telecominfraproject/wlan-pki-cert-scripts
+        path: wlan-pki-cert-scripts
+
+    - name: install dependencies
+      run: |
+        sudo apt-get install -y python3-pip
+        pip install paramiko scp allure-pytest
+
+    - name: create configuration.py file
+      run: |
+        cat << EOF > configuration.py
+        ${{ secrets.LAB_CONFIGURATION }}
+        EOF
+
+    - name: set redirector URL
+      env:
+        DIGICERT_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
+      run: |
+        for id in $(echo -e 'from configuration import CONFIGURATION\nfor ap in CONFIGURATION["${{ matrix.testbed }}"]["access_point"]: print(ap["serial"])' | python3)
+        do
+          ./wlan-pki-cert-scripts/digicert-change-ap-redirector.sh $id "${{ needs.deploy-controller.outputs.gateway_url }}"
+          current_redirector=$(./wlan-pki-cert-scripts/digicert-get-ap-redirector.sh $id)
+          if [[ "$current_redirector" != "${{ needs.deploy-controller.outputs.gateway_url }}" ]]; then
+            echo "Current redirector in DigiCert ($current_redirector) is different from the required one (${{ needs.deploy-controller.outputs.gateway_url }})"
+            exit 1
+          fi
+        done
+
+    - name: factory reset APs
+      run: |
+        set -x
+        AP_LEN=$(echo -e "from configuration import CONFIGURATION\nprint(len(CONFIGURATION['${{ matrix.testbed }}']['access_point']) - 1)" | python3)
+        for index in $(seq 0 $AP_LEN)
+        do
+          HOST=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['ip'])" | python3)
+          JUMPHOST=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['jumphost'])" | python3)
+          TTY=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['jumphost_tty'])" | python3)
+          PORT=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['port'])" | python3)
+          USERNAME=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['username'])" | python3)
+          PASSWORD=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['password'])" | python3)
+          cd wlan-testing/tools
+          python3 ap_tools.py --host $HOST --jumphost $JUMPHOST --tty $TTY --port $PORT --username $USERNAME --password $PASSWORD --cmd "jffs2reset -y -r"
+          cd ../..
+        done
+
+    - name: wait for APs to come up again
+      run: sleep 300
+
+  test:
+    runs-on: ubuntu-latest
+    needs: [ build, generate-matrix, deploy-controller ]
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson( needs.generate-matrix.outputs.matrix ) }}
     steps:
     - name: get EKS access credentials
       run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}
@@ -369,6 +452,7 @@ jobs:
         kubectl create ns $NAMESPACE
         kubectl config set-context --current --namespace=$NAMESPACE
         echo "::set-output name=name::${NAMESPACE}"
+
     - name: create configuration.py secret
       run: |
         cat << EOF > configuration.py
@@ -377,7 +461,8 @@ jobs:
         sed -i -r "s/'url': ('|\").*('|\")/'url': 'https:\/\/${{ needs.deploy-controller.outputs.sec_url }}:16001'/" configuration.py
         cat configuration.py
         kubectl create secret generic configuration --from-file=configuration=./configuration.py
-    - name: run sanity tests
+
+    - name: run tests
       run: |
         cat <<EOF | kubectl apply -f -
         apiVersion: batch/v1
@@ -386,17 +471,27 @@ jobs:
           name: "${{ steps.job.outputs.name }}"
         spec:
           template:
+            metadata:
+              annotations:
+                cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
             spec:
               containers:
               - name: tests
                 image: ${{ env.DOCKER_SERVER }}/cloud-sdk-nightly:${{ github.run_id }}
+                resources:
+                  requests:
+                    memory: "512Mi"
+                    cpu: "250m"
+                  limits:
+                    memory: "512Mi"
+                    cpu: "250m"
                 command:
                   - /bin/bash
                   - -x
                   - -c
                   - |
                     cd tests
-                    pytest -m "${{ github.event.inputs.marker_expression }}" -s -vvv --testbed="${{ github.event.inputs.testbeds }}" --alluredir=/tmp/allure-results
+                    pytest -m "${{ github.event.inputs.marker_expression }}" -s -vvv --testbed="${{ matrix.testbed }}" --alluredir=/tmp/allure-results
                     ret=\$?
                     # sleep some time to be able to download the Allure results
                     sleep 60
@@ -406,6 +501,12 @@ jobs:
                   mountPath: "/wlan-testing/tests/configuration.py"
                   subPath: configuration
                   readOnly: true
+              nodeSelector:
+                env: tests
+              tolerations:
+              - key: "tests"
+                operator: "Exists"
+                effect: "NoSchedule"
               imagePullSecrets:
               - name: tip-docker-registry-key
               restartPolicy: Never
@@ -432,112 +533,112 @@ jobs:
         echo "waiting for pod to exit"
         kubectl logs -f $podname >/dev/null 2>&1
         exit $(kubectl get pod $podname --output="jsonpath={.status.containerStatuses[].state.terminated.exitCode}")
+
     - name: print logs
       if: always()
       run: |
         podname=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -l job-name="${{ steps.job.outputs.name }}" | sed "s/pod\///")
         kubectl logs $podname
-#    - name: upload Allure results as artifact
-#      if: always()
-#      uses: actions/upload-artifact@v2
-#      with:
-#        name: allure-results-${{ matrix.testbed }}
-#        path: allure-results
+
+    - name: upload Allure results as artifact
+      if: always()
+      uses: actions/upload-artifact@v2
+      with:
+        name: allure-results-${{ matrix.testbed }}
+        path: allure-results
 
     - name: cleanup
       if: always()
       run: |
         kubectl delete ns "${{ steps.namespace.outputs.name }}" --wait=true
 
-#  report:
-#    runs-on: ubuntu-latest
-#    needs: [ test ]
-#    if: always()
-#    strategy:
-#      max-parallel: 1
-#      fail-fast: false
-#      matrix: ${{ fromJson( needs.generate-matrix.outputs.matrix ) }}
-#    steps:
-#    - name: install Allure CLI tool
-#      run: |
-#        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${{ env.ALLURE_CLI_VERSION }}/allure-commandline-${{ env.ALLURE_CLI_VERSION }}.tgz
-#        tar -xzf allure-commandline-${{ env.ALLURE_CLI_VERSION }}.tgz
-#
-#    - uses: actions/download-artifact@v2
-#      with:
-#        name: allure-results-${{ matrix.testbed }}
-#        path: allure-results
-#
-#    - name: checkout testing repo
-#      uses: actions/checkout@v2
-#      with:
-#        path: wlan-testing
-#
-#    - name: get reports branch
-#      uses: actions/checkout@v2
-#      continue-on-error: true
-#      with:
-#        ref: gh-pages
-#        path: reports
-#
-#    - name: copy history into results
-#      run: |
-#        if [ -e "reports/sanity/${{ matrix.testbed }}/latest" ] ; then
-#          cp -r reports/sanity/${{ matrix.testbed }}/latest/history/ allure-results/history
-#        fi
-#
-#    - name: add report metadata
-#      run: |
-#        cat << EOF >> allure-results/environment.properties
-#        Testbed=${{ matrix.testbed }}
-#        Tests.CommitId=$(cd wlan-testing && git rev-parse --short HEAD)
-#        CiRun.Id=${{ github.run_id }}
-#        CiRun.Number=${{ github.run_number }}
-#        CiRun.Url=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
-#        EOF
-#
-#    - name: generate Allure report
-#      run: allure-${{ env.ALLURE_CLI_VERSION }}/bin/allure generate
-#
-#    - name: upload Allure report as artifact
-#      uses: actions/upload-artifact@v2
-#      with:
-#        name: allure-report-${{ matrix.testbed }}
-#        path: allure-report
-#
-#    # doing this to be able to aggregate multiple reports together later on
-#    - name: copy results into report
-#      run: cp -r allure-results allure-report/results
-#
-#    - name: copy new report
-#      if: ${{ (github.event.inputs.marker_expression || 'ow_sanity_docker-compose') == 'ow_sanity_docker-compose' }}
-#      run: |
-#        mkdir -p reports/sanity/${{ matrix.testbed }}
-#        cp -Tr allure-report reports/sanity/${{ matrix.testbed }}/${{ github.run_number }}
-#
-#    - name: update latest symlink
-#      if: ${{ (github.event.inputs.marker_expression || 'ow_sanity_docker-compose') == 'ow_sanity_docker-compose' }}
-#      working-directory: reports/sanity/${{ matrix.testbed }}
-#      run: ln -fns ${{ github.run_number }} latest
-#
-#    - name: generate new index.html
-#      run: python wlan-testing/.github/tools/generate_directory_index.py -r reports
-#
-#    - name: commit reports update
-#      working-directory: reports
-#      run: |
-#        git config --global user.name "github-actions[bot]"
-#        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-#        git add .
-#        git commit -m "Automated deployment: $(date -u)"
-#
-#    - name: push
-#      if: github.ref == 'refs/heads/master'
-#      uses: ad-m/github-push-action@v0.6.0
-#      with:
-#        github_token: ${{ secrets.GITHUB_TOKEN }}
-#        branch: gh-pages
-#        directory: reports
+  report:
+    runs-on: ubuntu-latest
+    needs: [ test, generate-matrix ]
+    if: always()
+    strategy:
+      max-parallel: 1
+      fail-fast: false
+      matrix: ${{ fromJson( needs.generate-matrix.outputs.matrix ) }}
+    steps:
+    - name: install Allure CLI tool
+      run: |
+        wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/${{ env.ALLURE_CLI_VERSION }}/allure-commandline-${{ env.ALLURE_CLI_VERSION }}.tgz
+        tar -xzf allure-commandline-${{ env.ALLURE_CLI_VERSION }}.tgz
+
+    - uses: actions/download-artifact@v2
+      with:
+        name: allure-results-${{ matrix.testbed }}
+        path: allure-results
+
+    - name: checkout testing repo
+      uses: actions/checkout@v2
+      with:
+        path: wlan-testing
+
+    - name: get reports branch
+      uses: actions/checkout@v2
+      continue-on-error: true
+      with:
+        ref: gh-pages
+        path: reports
+
+    - name: copy history into results
+      run: |
+        if [ -e "reports/docker-compose/${{ github.event.inputs.marker_expression }}/${{ matrix.testbed }}/latest" ] ; then
+          cp -r reports/docker-compose/${{ github.event.inputs.marker_expression }}/${{ matrix.testbed }}/latest/history/ allure-results/history
+        fi
+
+    - name: add report metadata
+      run: |
+        cat << EOF >> allure-results/environment.properties
+        Testbed=${{ matrix.testbed }}
+        Tests.CommitId=$(cd wlan-testing && git rev-parse --short HEAD)
+        CiRun.Id=${{ github.run_id }}
+        CiRun.Number=${{ github.run_number }}
+        CiRun.Url=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
+        EOF
+
+    - name: generate Allure report
+      run: allure-${{ env.ALLURE_CLI_VERSION }}/bin/allure generate
+
+    - name: upload Allure report as artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: allure-report-${{ matrix.testbed }}
+        path: allure-report
+
+    # doing this to be able to aggregate multiple reports together later on
+    - name: copy results into report
+      run: cp -r allure-results allure-report/results
+
+    - name: copy new report
+      run: |
+        mkdir -p reports/docker-compose/${{ github.event.inputs.marker_expression }}/${{ matrix.testbed }}
+        cp -Tr allure-report reports/docker-compose/${{ github.event.inputs.marker_expression }}/${{ matrix.testbed }}/${{ github.run_number }}
+
+    - name: update latest symlink
+      working-directory: reports/docker-compose/${{ github.event.inputs.marker_expression }}/${{ matrix.testbed }}
+      run: ln -fns ${{ github.run_number }} latest
+
+    - name: generate new index.html
+      run: python wlan-testing/.github/tools/generate_directory_index.py -r reports
+
+    - name: commit reports update
+      working-directory: reports
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+        git add .
+        git commit -m "Automated deployment: $(date -u)"
+
+    - name: push
+      if: github.ref == 'refs/heads/master'
+      uses: ad-m/github-push-action@v0.6.0
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: gh-pages
+        directory: reports
 
   delete-docker-image:
     needs: [ test ]
@@ -563,3 +664,67 @@ jobs:
 
     - name: Delete namespace
       run: kubectl delete ns --ignore-not-found=true "openwifi-docker-compose-${{ github.run_id }}"
+
+  reset-redirector-url:
+    needs: [ set-redirector-url, test, generate-matrix ]
+    if: always()
+    strategy:
+      fail-fast: false
+      matrix: ${{ fromJson( needs.generate-matrix.outputs.matrix ) }}
+    runs-on: self-hosted
+    steps:
+    - name: checkout testing repo
+      uses: actions/checkout@v2
+      with:
+        repository: Telecominfraproject/wlan-testing
+        path: wlan-testing
+        ref: WIFI-3620
+
+    - name: checkout pki cert scripts repo
+      uses: actions/checkout@v2
+      with:
+        repository: Telecominfraproject/wlan-pki-cert-scripts
+        path: wlan-pki-cert-scripts
+
+    - name: install dependencies
+      run: |
+        pip install paramiko scp allure-pytest
+
+    - name: create configuration.py file
+      run: |
+        cat << EOF > configuration.py
+        ${{ secrets.LAB_CONFIGURATION }}
+        EOF
+
+    - name: reset redirector URL
+      env:
+        DIGICERT_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
+      run: |
+        for id in $(echo -e 'from configuration import CONFIGURATION\nfor ap in CONFIGURATION["${{ matrix.testbed }}"]["access_point"]: print(ap["serial"])' | python3)
+        do
+          ./wlan-pki-cert-scripts/digicert-change-ap-redirector.sh $id gw-qa01.cicd.lab.wlan.tip.build
+          current_redirector=$(./wlan-pki-cert-scripts/digicert-get-ap-redirector.sh $id)
+          if [[ "$current_redirector" != "gw-qa01.cicd.lab.wlan.tip.build" ]]; then
+            echo "Current redirector in DigiCert ($current_redirector) is different from the required one (gw-qa01.cicd.lab.wlan.tip.build)"
+            exit 1
+          fi
+        done
+
+    - name: factory reset APs
+      run: |
+        AP_LEN=$(echo -e "from configuration import CONFIGURATION\nprint(len(CONFIGURATION['${{ matrix.testbed }}']['access_point']) - 1)" | python3)
+        for index in $(seq 0 $AP_LEN)
+        do
+          HOST=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['ip'])" | python3)
+          JUMPHOST=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['jumphost'])" | python3)
+          TTY=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['jumphost_tty'])" | python3)
+          PORT=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['port'])" | python3)
+          USERNAME=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['username'])" | python3)
+          PASSWORD=$(echo -e "from configuration import CONFIGURATION\nprint(CONFIGURATION['${{ matrix.testbed }}']['access_point'][$index]['password'])" | python3)
+          cd wlan-testing/tools
+          python3 ap_tools.py --host $HOST --jumphost $JUMPHOST --tty $TTY --port $PORT --username $USERNAME --password $PASSWORD --cmd "jffs2reset -y -r"
+          cd ../..
+        done
+
+    - name: wait for APs to come up again
+      run: sleep 300
