Wifi 13063 (#861)
* removed udaya and replaced test-eap104 from advanced2 to basic4

Signed-off-by: anil-tegala <anil.tegala@candelatech.com>

* removed ap's from advanced runs and moved to basic testbeds

Signed-off-by: anil-tegala <anil.tegala@candelatech.com>

---------

Signed-off-by: anil-tegala <anil.tegala@candelatech.com>

diff --git a/.github/workflows/quali.yml b/.github/workflows/quali.yml
--- a/.github/workflows/quali.yml
+++ b/.github/workflows/quali.yml
@@ -22,7 +22,7 @@ on:
         description: "revision of the Open Wifi Helm chart"
       ap_models:
         required: true
-        default: "cig_wf188n,cig_wf196,udaya_a5-id2,edgecore_ecw5211,indio_um-305ac,hfcl_ion4xe,edgecore_eap101"
+        default: "cig_wf188n,cig_wf196,edgecore_ecw5211,indio_um-305ac,edgecore_eap101"
         description: "the AP models to test"
       ap_version:
         required: true
@@ -76,10 +76,10 @@ jobs:
           echo "Current slot is $SLOT"
           if [[ "$SLOT" -eq "0" ]]; then
             echo "Choosing first slot since $SLOT == 0"
-            AP_MODELS="${{ github.event.inputs.ap_models || 'cig_wf188n, cig_wf196, udaya_a5-id2, edgecore_eap104, edgecore_eap101' }}"
+            AP_MODELS="${{ github.event.inputs.ap_models || 'cig_wf188n, cig_wf196, edgecore_eap101, edgecore_ecw5211, indio_um-305ac' }}"
           else
             echo "Choosing second slot since $SLOT != 0"
-            AP_MODELS="${{ github.event.inputs.ap_models || 'edgecore_ecw5211, indio_um-305ac, edgecore_oap101_6e, edgecore_eap102' }}"
+            AP_MODELS="${{ github.event.inputs.ap_models || 'edgecore_oap101_6e, edgecore_eap102, edgecore_eap101, edgecore_eap104, indio_um-305ac' }}"
           fi
           echo "List of AP models to test - $AP_MODELS"
           AP_MODELS=$(echo $AP_MODELS | sed "s/,/\",\"/g" | sed 's/^/[\"/g' | sed 's/$/\"]/g')
@@ -307,102 +307,102 @@ jobs:
         if: failure()
         run: kubectl -n openwifi-qa01 logs deployment/owsec
 
-  test-udaya-a5-id2:
-    needs: [ "vars", "build" ]
-    runs-on: ubuntu-latest
-    if: "!cancelled() && contains(fromJSON(needs.vars.outputs.ap_models), 'udaya_a5-id2')"
-    env:
-      AP_MODEL: udaya_a5-id2
-    steps:
-      - name: Set AP model output
-        id: ap_model
-        run: |
-          echo "model=${AP_MODEL}" >> $GITHUB_OUTPUT
-
-      - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.8"
-
-      # TODO WIFI-7839 delete when issue is resolved on AWS CLI side
-      - name: install kubectl
-        run: |
-          curl -s -LO "https://dl.k8s.io/release/v1.27.6/bin/linux/amd64/kubectl"
-          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
-
-      - name: get EKS access credentials
-        run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}
-
-      - name: prepare namespace name
-        id: namespace
-        run: |
-          NAMESPACE="testing-${{ github.run_id }}-$(echo ${{ steps.ap_model.outputs.model }} | tr '[:upper:]' '[:lower:]' | tr '_' '-')"
-          echo "name=${NAMESPACE}" >> $GITHUB_OUTPUT
-
-      - name: prepare configuration
-        run: |
-          cat << EOF > lab_info.json
-          ${{ secrets.LAB_INFO_JSON }}
-          EOF
-
-      #          DYN_CONFIG="$(python .quali/get_configuration.py --json ${{ steps.reservation.outputs.identifier }})"
-      #          jq ".CONFIGURATION.basic=$DYN_CONFIG" lab_info.json > lab_info.json.tmp && mv lab_info.json.tmp lab_info.json
-      #
-      #          # overwrite configuration value from Quali
-      #          if [ ${{ needs.vars.outputs.existing_controller }} != '' ]
-      #          then
-      #            jq '.CONFIGURATION.basic.controller.url="https://sec-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build:16001"' lab_info.json > lab_info.json.tmp && mv lab_info.json.tmp lab_info.json
-      #          fi
-
-      - name: run tests
-        uses: ./.github/actions/run-tests
-        with:
-          namespace: ${{ steps.namespace.outputs.name }}
-          testbed: basic-3
-          marker_expression: "${{ needs.vars.outputs.marker_expression }}"
-          configuration_file: "./lab_info.json"
-          testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
-          additional_args: '-o firmware="${{ needs.vars.outputs.ap_version }}"'
-          allure_results_artifact_name: "allure-results-${{ steps.ap_model.outputs.model }}"
-          dns_records_to_resolve: "sec-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build gw-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build fms-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build"
-
-      # necessary because if conditionals in composite actions are currently not respected
-      - name: get tests logs
-        if: always()
-        continue-on-error: true
-        run: |
-          podname=$(kubectl get pods -n ${{ steps.namespace.outputs.name }} --no-headers -o custom-columns=":metadata.name" -l job-name=testing | sed "s/pod\///")
-          kubectl logs --timestamps -n ${{ steps.namespace.outputs.name }} $podname || true
-
-      - name: delete namespace
-        if: always()
-        continue-on-error: true
-        run: kubectl delete ns --ignore-not-found=true --wait ${{ steps.namespace.outputs.name }}
-
-      - name: show gw logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owgw
-
-      - name: show fms logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owfms
-
-      - name: show prov logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owprov
-
-      - name: show analytics logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owanalytics
-
-      - name: show subscription (userportal) logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owsub
-
-      - name: show sec logs
-        if: failure()
-        run: kubectl -n openwifi-qa01 logs deployment/owsec
+#  test-udaya-a5-id2:
+#    needs: [ "vars", "build" ]
+#    runs-on: ubuntu-latest
+#    if: "!cancelled() && contains(fromJSON(needs.vars.outputs.ap_models), 'udaya_a5-id2')"
+#    env:
+#      AP_MODEL: udaya_a5-id2
+#    steps:
+#      - name: Set AP model output
+#        id: ap_model
+#        run: |
+#          echo "model=${AP_MODEL}" >> $GITHUB_OUTPUT
+#
+#      - uses: actions/checkout@v3
+#      - name: Set up Python
+#        uses: actions/setup-python@v4
+#        with:
+#          python-version: "3.8"
+#
+#      # TODO WIFI-7839 delete when issue is resolved on AWS CLI side
+#      - name: install kubectl
+#        run: |
+#          curl -s -LO "https://dl.k8s.io/release/v1.27.6/bin/linux/amd64/kubectl"
+#          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+#
+#      - name: get EKS access credentials
+#        run: aws eks update-kubeconfig --name ${{ env.AWS_EKS_NAME }}
+#
+#      - name: prepare namespace name
+#        id: namespace
+#        run: |
+#          NAMESPACE="testing-${{ github.run_id }}-$(echo ${{ steps.ap_model.outputs.model }} | tr '[:upper:]' '[:lower:]' | tr '_' '-')"
+#          echo "name=${NAMESPACE}" >> $GITHUB_OUTPUT
+#
+#      - name: prepare configuration
+#        run: |
+#          cat << EOF > lab_info.json
+#          ${{ secrets.LAB_INFO_JSON }}
+#          EOF
+#
+#      #          DYN_CONFIG="$(python .quali/get_configuration.py --json ${{ steps.reservation.outputs.identifier }})"
+#      #          jq ".CONFIGURATION.basic=$DYN_CONFIG" lab_info.json > lab_info.json.tmp && mv lab_info.json.tmp lab_info.json
+#      #
+#      #          # overwrite configuration value from Quali
+#      #          if [ ${{ needs.vars.outputs.existing_controller }} != '' ]
+#      #          then
+#      #            jq '.CONFIGURATION.basic.controller.url="https://sec-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build:16001"' lab_info.json > lab_info.json.tmp && mv lab_info.json.tmp lab_info.json
+#      #          fi
+#
+#      - name: run tests
+#        uses: ./.github/actions/run-tests
+#        with:
+#          namespace: ${{ steps.namespace.outputs.name }}
+#          testbed: basic-3
+#          marker_expression: "${{ needs.vars.outputs.marker_expression }}"
+#          configuration_file: "./lab_info.json"
+#          testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
+#          additional_args: '-o firmware="${{ needs.vars.outputs.ap_version }}"'
+#          allure_results_artifact_name: "allure-results-${{ steps.ap_model.outputs.model }}"
+#          dns_records_to_resolve: "sec-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build gw-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build fms-${{ needs.vars.outputs.existing_controller }}.cicd.lab.wlan.tip.build"
+#
+#      # necessary because if conditionals in composite actions are currently not respected
+#      - name: get tests logs
+#        if: always()
+#        continue-on-error: true
+#        run: |
+#          podname=$(kubectl get pods -n ${{ steps.namespace.outputs.name }} --no-headers -o custom-columns=":metadata.name" -l job-name=testing | sed "s/pod\///")
+#          kubectl logs --timestamps -n ${{ steps.namespace.outputs.name }} $podname || true
+#
+#      - name: delete namespace
+#        if: always()
+#        continue-on-error: true
+#        run: kubectl delete ns --ignore-not-found=true --wait ${{ steps.namespace.outputs.name }}
+#
+#      - name: show gw logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owgw
+#
+#      - name: show fms logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owfms
+#
+#      - name: show prov logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owprov
+#
+#      - name: show analytics logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owanalytics
+#
+#      - name: show subscription (userportal) logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owsub
+#
+#      - name: show sec logs
+#        if: failure()
+#        run: kubectl -n openwifi-qa01 logs deployment/owsec
 
   test-edgecore-ecw5211:
     needs: [ "vars", "build" ]
@@ -650,7 +650,7 @@ jobs:
         uses: ./.github/actions/run-tests
         with:
           namespace: ${{ steps.namespace.outputs.name }}
-          testbed: advanced-1a
+          testbed: basic-4a
           marker_expression: "${{ needs.vars.outputs.marker_expression }}"
           configuration_file: "./lab_info.json"
           testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
@@ -747,7 +747,7 @@ jobs:
         uses: ./.github/actions/run-tests
         with:
           namespace: ${{ steps.namespace.outputs.name }}
-          testbed: advanced-1b
+          testbed: basic-1a
           marker_expression: "${{ needs.vars.outputs.marker_expression }}"
           configuration_file: "./lab_info.json"
           testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
@@ -844,7 +844,7 @@ jobs:
         uses: ./.github/actions/run-tests
         with:
           namespace: ${{ steps.namespace.outputs.name }}
-          testbed: advanced-1c
+          testbed: basic-3
           marker_expression: "${{ needs.vars.outputs.marker_expression }}"
           configuration_file: "./lab_info.json"
           testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
@@ -943,7 +943,7 @@ jobs:
         uses: ./.github/actions/run-tests
         with:
           namespace: ${{ steps.namespace.outputs.name }}
-          testbed: advanced-2a
+          testbed: basic-3a
           marker_expression: "${{ needs.vars.outputs.marker_expression }}"
           configuration_file: "./lab_info.json"
           testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
@@ -1041,7 +1041,7 @@ jobs:
         uses: ./.github/actions/run-tests
         with:
           namespace: ${{ steps.namespace.outputs.name }}
-          testbed: advanced-2c
+          testbed: basic-2a
           marker_expression: "${{ needs.vars.outputs.marker_expression }}"
           configuration_file: "./lab_info.json"
           testing_docker_image: tip-tip-wlan-cloud-docker-repo.jfrog.io/cloud-sdk-nightly:${{ github.run_id }}
@@ -1092,7 +1092,7 @@ jobs:
   report:
     if: "!cancelled()"
     runs-on: ubuntu-latest
-    needs: [vars, test-cig-wf188n, test-cig-wf196, test-udaya-a5-id2, test-edgecore-ecw5211, test-indio-um-305ac, test-edgecore-eap104, test-edgecore-oap101-6e, test-hfcl-ion4xe, test-edgecore-eap101, test-edgecore-eap102]
+    needs: [vars, test-cig-wf188n, test-cig-wf196, test-edgecore-ecw5211, test-indio-um-305ac, test-edgecore-eap104, test-edgecore-oap101-6e, test-hfcl-ion4xe, test-edgecore-eap101, test-edgecore-eap102]
     strategy:
       fail-fast: false
       matrix:
@@ -1143,7 +1143,7 @@ jobs:
 
   # Cleanup
   cleanup:
-    needs: [test-cig-wf188n, test-cig-wf196, test-udaya-a5-id2, test-edgecore-ecw5211, test-indio-um-305ac, test-edgecore-eap104, test-edgecore-oap101-6e, test-hfcl-ion4xe, test-edgecore-eap101, test-edgecore-eap102]
+    needs: [test-cig-wf188n, test-cig-wf196, test-edgecore-ecw5211, test-indio-um-305ac, test-edgecore-eap104, test-edgecore-oap101-6e, test-hfcl-ion4xe, test-edgecore-eap101, test-edgecore-eap102]
     runs-on: ubuntu-latest
     if: always()
     steps:
