[WIFI-5119] Chg: use digicert-get-ap-redirector to assure correct redirector after setting and resetting in dynamic sanity

diff --git a/.github/workflows/uc_sanity_dynamic.yml b/.github/workflows/uc_sanity_dynamic.yml
--- a/.github/workflows/uc_sanity_dynamic.yml
+++ b/.github/workflows/uc_sanity_dynamic.yml
@@ -189,7 +189,11 @@ jobs:
         for id in $(echo -e 'from configuration import CONFIGURATION\nfor ap in CONFIGURATION["${{ matrix.testbed }}"]["access_point"]: print(ap["serial"])' | python3)
         do
           ./wlan-pki-cert-scripts/digicert-change-ap-redirector.sh $id "${{ needs.deploy-controller.outputs.gateway_url }}"
-          echo "Exit code - $?"
+          current_redirector=$(./wlan-pki-cert-scripts/digicert-get-ap-redirector.sh $id)
+          if [[ "$current_redirector" != "${{ needs.deploy-controller.outputs.gateway_url }}" ]]; then
+            echo "Current redirector in DigiCert ($current_redirector) is different from the required one (${{ needs.deploy-controller.outputs.gateway_url }})"
+            exit 1
+          fi
         done
 
     - name: factory reset APs
@@ -471,7 +475,11 @@ jobs:
         for id in $(echo -e 'from configuration import CONFIGURATION\nfor ap in CONFIGURATION["${{ matrix.testbed }}"]["access_point"]: print(ap["serial"])' | python3)
         do
           ./wlan-pki-cert-scripts/digicert-change-ap-redirector.sh $id gw-qa01.cicd.lab.wlan.tip.build
-          echo "Exit code - $?"
+          current_redirector=$(./wlan-pki-cert-scripts/digicert-get-ap-redirector.sh $id)
+          if [[ "$current_redirector" != "${{ needs.deploy-controller.outputs.gateway_url }}" ]]; then
+            echo "Current redirector in DigiCert ($current_redirector) is different from the required one (${{ needs.deploy-controller.outputs.gateway_url }})"
+            exit 1
+          fi
         done
 
     - name: factory reset APs
